[theme]
primaryColor = "#4a7c59"         # A muted green for a professional tone
backgroundColor = "#f8f9fa"      # Light gray for minimalistic feel
secondaryBackgroundColor = "#ffffff" # White for contrast against the main background
textColor = "#333333"            # Dark gray for readability
font = "monospace"
